# Generated by Django 4.1a1 on 2022-06-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=25)),
                ('units_in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField(verbose_name='Minimum Units to maintain in stock')),
                ('discontinued', models.BooleanField(default=False, verbose_name='Yes means item is no longer available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spare.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('item_name',),
            },
        ),
        migrations.CreateModel(
            name='ItemMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_contained', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.item')),
            ],
            options={
                'verbose_name': 'ItemMeasurement',
                'verbose_name_plural': 'ItemMeasurements',
            },
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date_in', models.DateField()),
                ('date_out', models.CharField(blank=True, max_length=10, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=10, null=True)),
                ('car_model', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supervisor', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage_in', models.CharField(blank=True, max_length=50, null=True)),
                ('mileage_out', models.CharField(blank=True, max_length=50, null=True)),
                ('brought_in_by', models.CharField(max_length=50)),
                ('Taken_out_by', models.CharField(max_length=50)),
                ('fuel_gauge_in', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_gauge_out', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_nuts', models.IntegerField()),
                ('car_description', models.TextField()),
                ('customer_approval', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Approved', max_length=50)),
                ('dash_light_on', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=50)),
                ('car_type', models.CharField(choices=[('SALOON', 'SALOON'), ('STATION WAGON', 'STATION WAGON'), ('SUV', 'SUV'), ('PICKUP', 'PICKUP')], default='SUV', max_length=50)),
                ('items_in_car', models.TextField()),
            ],
            options={
                'verbose_name': 'jobcard',
                'verbose_name_plural': 'jobcards',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, verbose_name='Measurement')),
            ],
            options={
                'verbose_name': 'Measurement',
                'verbose_name_plural': 'Measurements',
                'ordering': ('unit_name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='spare.service')),
            ],
            options={
                'verbose_name': 'ServicePrice',
                'verbose_name_plural': 'ServicePrices',
            },
        ),
        migrations.CreateModel(
            name='JobCardService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.jobcard')),
                ('service_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_card_services', to='spare.serviceprice')),
            ],
            options={
                'verbose_name': 'JobCardService',
                'verbose_name_plural': 'JobCardServices',
            },
        ),
        migrations.CreateModel(
            name='JobCardItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_card_items', to='spare.itemmeasurement')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.jobcard')),
            ],
            options={
                'verbose_name': 'JobCardItem',
                'verbose_name_plural': 'JobCardItems',
            },
        ),
        migrations.AddField(
            model_name='itemmeasurement',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spare.measurement'),
        ),
        migrations.CreateModel(
            name='ItemInCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_sCode', to='spare.jobcard')),
            ],
            options={
                'verbose_name': 'ItemInCar',
                'verbose_name_plural': 'ItemInCars',
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('date_in', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pic')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_Code', to='spare.jobcard')),
            ],
            options={
                'verbose_name': 'Damage',
                'verbose_name_plural': 'Damages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemmeasurement',
            unique_together={('item', 'measurement')},
        ),
    ]
