# Generated by Django 4.1a1 on 2022-06-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemInCar',
        ),
    ]
