# Generated by Django 4.1b1 on 2022-06-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0002_delete_itemincar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcarditems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_mesurement', to='spare.itemmeasurement'),
        ),
        migrations.AlterField(
            model_name='jobcarditems',
            name='jobcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_card_items', to='spare.jobcard'),
        ),
    ]
