# Generated by Django 4.1b1 on 2022-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0003_alter_jobcarditems_items_alter_jobcarditems_jobcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='Taken_out_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
