# Generated by Django 3.0.7 on 2023-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0007_auto_20230609_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarditems',
            name='item_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
