# Generated by Django 3.0.7 on 2023-07-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0008_jobcarditems_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarditems',
            name='description',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
