# Generated by Django 3.0.7 on 2023-07-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0010_jobcardservice_service_price_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardservice',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='spare.Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcardservice',
            name='service_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_card_service', to='spare.ServicePrice'),
        ),
    ]
