# Generated by Django 3.0.7 on 2023-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0011_auto_20230707_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcarditems',
            name='items',
            field=models.CharField(max_length=100),
        ),
    ]
