# Generated by Django 3.0.7 on 2023-07-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare', '0012_auto_20230724_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Car', 'Car'), ('Garage', 'Garage'), ('Others', 'Others')], default='Car', max_length=50)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
